# Generated by Django 3.0.5 on 2020-04-07 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('murderer', models.CharField(default='Blank', max_length=13)),
                ('weapon', models.CharField(default='Blank', max_length=13)),
                ('room', models.CharField(default='Blank', max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='', max_length=1)),
                ('card_text', models.CharField(default='Blank', max_length=13)),
                ('player', models.ForeignKey(default='Nobody', on_delete=django.db.models.deletion.CASCADE, to='players.Player')),
            ],
        ),
    ]
