# Generated by Django 3.0.5 on 2020-04-07 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s1', models.BooleanField(default=False, verbose_name='Col. Mustard')),
                ('s2', models.BooleanField(default=False, verbose_name='Prof. Plum')),
                ('s3', models.BooleanField(default=False, verbose_name='Mr. Green')),
                ('s4', models.BooleanField(default=False, verbose_name='Mrs. Peacock')),
                ('s5', models.BooleanField(default=False, verbose_name='Miss Scarlet')),
                ('s6', models.BooleanField(default=False, verbose_name='Mrs. White')),
                ('w1', models.BooleanField(default=False, verbose_name='Knife')),
                ('w2', models.BooleanField(default=False, verbose_name='Candlestick')),
                ('w3', models.BooleanField(default=False, verbose_name='Revolver')),
                ('w4', models.BooleanField(default=False, verbose_name='Rope')),
                ('w5', models.BooleanField(default=False, verbose_name='Lead Pipe')),
                ('w6', models.BooleanField(default=False, verbose_name='Wrench')),
                ('r1', models.BooleanField(default=False, verbose_name='Hall')),
                ('r2', models.BooleanField(default=False, verbose_name='Lounge')),
                ('r3', models.BooleanField(default=False, verbose_name='Dining Room')),
                ('r4', models.BooleanField(default=False, verbose_name='Kitchen')),
                ('r5', models.BooleanField(default=False, verbose_name='Ballroom')),
                ('r6', models.BooleanField(default=False, verbose_name='Conservatory')),
                ('r7', models.BooleanField(default=False, verbose_name='Billiard Room')),
                ('r8', models.BooleanField(default=False, verbose_name='Library')),
                ('r9', models.BooleanField(default=False, verbose_name='Study')),
                ('player', models.ForeignKey(default='Nobody', on_delete=django.db.models.deletion.CASCADE, to='players.Player')),
            ],
        ),
    ]
