# Generated by Django 3.0.5 on 2020-04-19 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_playersheet'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedWith',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared_with', models.BooleanField(default=False)),
                ('player', models.ForeignKey(default='Nobody', on_delete=django.db.models.deletion.CASCADE, to='players.Player')),
            ],
        ),
    ]
