# Generated by Django 3.0.5 on 2020-04-19 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_sharedwith'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedwith',
            name='card_text',
            field=models.CharField(default='Blank', max_length=13),
        ),
    ]
